### PR TITLE
Promise based start, stop, startAll, stopAll

### PR DESCRIPTION
**Pull request by allain**
Assumes a global Promise object is available.

Figured code might be a better way of communicating the ideas.

Supports:
```js
Core.start('a').then(function(result) {
  // Even if init did not return anything
  console.log('module a started', result);
});

Core.startAll().then(function(result) {
  console.log(result); // an object that maps module names to their resolved values (may be undefined)
});

Core.stop('a').then(function(result) {
  // Even if init did not return anything
  console.log('module a started', result);
});

Core.stopAll().then(function(result) {
  console.log(result); // an object that maps module names to their resolved values (may be undefined)
});
```

### CODE REVIEW

**Comment by jaetask** [comment]
Yup. That looks spot on to me. Simple and clean.

**Comment by mauriciosoares** [comment]
Hey @allain, I agree with @jaetask, that's an clean and elegant solution, also I've never worked with the native Promises, thanks for teaching me that.

But I have to argue about some things in your solution, first, according to the [mdn docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), the `Promise` object doesn't seem to support IE (in any version :/), also is not supported by Android, so I suppose we are gonna need a polyfill on that, which I'd love to work on.

And other thing, we talked in the issue #26 about handling async stuff, I mean if I do an ajax request in the init method, the callback in start will get triggered even if the ajax has not finished, do you see that as a problem?

**Comment by allain** [comment]
Correct Promises will need to be polyfilled. I'd put in a comment saying
that the code assumed a global Promise implementation.

If methods in the sandbox (which I haven't deep dived yet) returned
promises then in the init you could do something like this:

... init = function(sandbox) {
  return sandbox.ajaxRequest(....).then(function(response) {
    /// process response and finish setup
    return true;
  }});
}

**Comment by mauriciosoares** [comment]
Cool, I'll check out some promises polyfill.

For the ajax handling I'd have to that internally in Core.js, I'll stick to simple promises at first, and then take a look how to implement that inside Core.

You mind if I don't merge this PR? since there's some work to be done with the polyfills and tests?

**Pull request closed without merging**
